name: Scan Table Output

on:
  push:
    branches:
      - main
      - develop

jobs:
  trivy:
    name: Trivy
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write # Required to create an issue
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          output: "trivy-report.txt"
          exit-code: "1"
          ignore-unfixed: true
          scanners: "vuln,secret,misconfig"
          severity: "HIGH,CRITICAL"
      
      - name: Prepare Report Data
        if: failure() && steps.trivy_scan.outcome == 'failure'
        run: |
          DELIMITER=$(openssl rand -hex 8)
          echo "REPORT_DATA<<${DELIMITER}" >> $GITHUB_ENV
          cat trivy-report.txt >> $GITHUB_ENV
          echo "${DELIMITER}" >> $GITHUB_ENV

      - name: Create Issue if Vulnerabilities Found
        if: failure() && steps.trivy_scan.outcome == 'failure'
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_ACTOR: ${{ github.actor }}   
          GITHUB_RUN_ID: ${{ github.run_id }}
          REPORT_DATA: ${{ env.REPORT_DATA }}
        with:
          filename: .github/ISSUE_TEMPLATE/vuln_report.md
          update_existing: true
      
      - name: Close Issue if Vulnerabilities are Resolved
        run: |
          # Find issue number
          ISSUE_NUMBER=$(gh issue list --search "($GITHUB_REF_NAME) Security Alert: High/Critical Vulnerabilities Found" -l "security" | awk '{print $1}')
          
          # Exit if issue does not exist
          if [[ -z "$ISSUE_NUMBER" ]]; then
            echo "No matching issue found. Exiting gracefully."
            exit 0
          fi

          # Close the issue with comment
          COMMIT_MSG=$(git log -1 --pretty=%s)
          gh issue close "$ISSUE_NUMBER" --comment "✅ **Vulnerability Scan Passed**
          This issue was automatically closed because a Trivy scan found 0 vulnerabilities.
          **Verified in Commit:** [$COMMIT_MSG]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)
          **Scan Date:** $(date +'%Y-%m-%d')"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Echo Trivy Success
        run: echo "No High or Critical vulnerabilities found."

      - name: Echo Trivy Failure
        if: failure() && steps.trivy_scan.outcome == 'failure'
        run: echo "Vulnerabilities were found. Failing build."